// src/modules/menu/menu-item.mapper.ts

import { MenuItemRow } from "@/config/models";
import { MenuItemResponseDto, MenuItemListResponseDto, CreateMenuItemDto } from "../dtos/MenuItemDtos";
import { MenuItemEntity } from "../entity/Menu.Entity";

export class MenuItemMapper {

  // ── DB row → Domain Entity ─────────────────────────────────────────
  static toDomain(row: MenuItemRow): MenuItemEntity {
    return new MenuItemEntity(
      row.id,
      row.name,
      row.description  ?? null,
      row.category,
      row.image_url    ?? null,
      row.is_available,
      row.created_at,
      row.updated_at,
    );
  }

    static toCreateEntity(dto: CreateMenuItemDto): MenuItemEntity {
  
    return new MenuItemEntity(
      dto.id!,                     // id will be generated by DB
      dto.name,
      dto.description ?? null,
      dto.category,
      dto.image_url ?? null,
      dto.is_available ?? true, // default available
      new Date(0),                     // created_at
      new Date(0)                      // updated_at
    );
  }

  // ── Domain Entity → Response DTO ───────────────────────────────────
  static toResponseDto(entity: MenuItemEntity): MenuItemResponseDto {
    return {
      id:           entity.id,
      name:         entity.name,
      description:  entity.description,
      category:     entity.category,
      image_url:    entity.imageUrl,
      is_available: entity.is_available,
      created_at:   entity.createdAt.toISOString(),
      updated_at:   entity.updatedAt.toISOString(),
    };
  }

   // ── Domain Entity → DB Persistence ─────────────────────────────────
  static toPersistence(entity: MenuItemEntity): MenuItemRow {
    return {
      id: entity.id,
      name: entity.name,
      description: entity.description,
      category: entity.category,
      image_url: entity.imageUrl,
      is_available: entity.is_available,
      created_at: entity.createdAt,
      updated_at: entity.updatedAt,
    };
  }

  // ── DB rows → Domain Entities ──────────────────────────────────────
  static toEntityArray(rows: MenuItemRow[]): MenuItemEntity[] {
    return rows.map(this.toDomain);
  }

  // ── Domain Entities → Response DTOs ────────────────────────────────
  static toResponseDtoArray(entities: MenuItemEntity[]): MenuItemResponseDto[] {
         return entities.map(this.toResponseDto);
  }

    // ✅ NEW
  static toListResponseDto(entities: MenuItemEntity[],total: number): MenuItemListResponseDto {
    return {
      items: entities.map(this.toResponseDto),
      total,
    };
  }

}